import UIKit

var ilce: String = "Bakırköy"
var kıta: String = "Asya"
var faks: String = "0216 123 45 67"
var postaKodu: String = "34728"
var instaAdresi: String = "@oyaaozcan"
var calistiginBolum: String = "Mobil Developer"
var musteriSoyadi: String = "Özcan"
var telefonModeli: String = "iPhone 11"
var dergiAdi: String = "Bilim Cocuk"
var videoAdi: String = "Swift Videosu"
var dosyaAdi: String = "Proje.docx"
var medeniHal: String = "Bekar"
var videoYorumu = "Çok güzel bir video"
var resimFormati: String = "JPG"
var renk: String = "Yeşil"
var renkKodu: String = "#0b99fb"
var bilgisayarModeli: String = "MacBook Air"
var mahalleAdi: String = "Atatürk Mahallesi"
var otobusHatti: String = "72T"
var kargoTakipNo: String = "123456789"
var kuponKodu: String = "INDIRIM50"
var yemekAdi: String = "Köfte"
var sirket: String = "Blue Python"
var kullanımSuresi: String = "2 yıl"
var ödemeSaati: String = "15:30"
var borc:Int = 1000
var urunMiktari: Int = 30
var satilanMiktar: Int = 30
var daireSayisi: Int = 12
var enlem: Int = 41
var boylam: Int = 29
var ekranBoyutu: Int = 15
var kullanilanDakika: Int = 120
var kuponSuresi: Int = 30
var odemeMiktari: Double = 500.50
var zamMiktari: Double = 150.25
var urunFiyati: Double = 100.99
var muzikSuresi: Double = 3.45
var mekanPuani: Double = 4.8
var basinc: Double = 1012.5
var eftMiktari: Double = 1200.35
var dogumTarihi: String = "28.09.1998"
var basimTarihi: String = "10.10.2023"
var odemeSaati: String = "15.00"
var odemeGunu: String = "25.09.2024"
var yolculukCikisTarihi: String = "11.11.2024"
var faturaTarihi: String = "10.10.2024"
var etkinlikGunu: String = "12.12.2024"
var kullanimSuresi: String = "2 yıl"


